# to install run:
# ansible-galaxy collection install -r requirements.yaml
---
collections:
  - name: ansible.posix
    version: 1.5.4
  # - name: community.general
  #   version: 7.5.0
  # - name: ansible.netcommon
  #   version: 5.3.0
