---
# code: language=ansible
- name: Ensure the mount point directory exists
  become: true
  ansible.builtin.file:
    path: /secrets
    state: directory
    mode: "0755"

- name: Add tmpfs entry to /etc/fstab
  become: true
  ansible.posix.mount:
    path: /secrets
    src: tmpfs
    fstype: tmpfs
    opts: defaults,atime,size=256M,mode=1777,nodev,nosuid
    state: present

# - name: Mount the tmpfs filesystem
#   become: true
#   ansible.builtin.command: mount /secrets
  # The `mount` command is used to apply the fstab changes immediately
  # This task may be omitted if only setting up for reboot
