- name: Install Pi-hole on router
  hosts: router

  tasks:
    - name: Ensure /opt/pi-hole exists
      become: yes
      file:
        path: /opt/pi-hole
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"

    - name: Copy docker-compose.yaml to /opt/pi-hole
      copy:
        src: ./docker-compose.yaml
        dest: /opt/pi-hole/docker-compose.yaml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"
      register: copy_pihole_compose

    - name: Run Docker Compose to set up the container
      shell: |
        cd /opt/pi-hole
        docker compose up -d
      args:
        executable: /bin/bash
      register: docker_compose_result
      changed_when: "'Creating' in docker_compose_result.stdout or 'Starting' in docker_compose_result.stdout"
      when: copy_pihole_compose.changed

    - name: Configure /etc/resolv.conf
      become: yes
      copy:
        src: ./resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"
