- name: Install tools
  become: yes
  apt:
    update_cache: yes
    autoremove: yes
    name:
      - ca-certificates
      - curl
      - openssh-server
      - vim
      - htop
      - dnsutils
      - iperf3
      - iptables
      - man
      - zip
      - unzip
      - wget
      - gnupg2
      - rsync
      - debian-archive-keyring
      - python3-pip
      - python3-venv
      - python-is-python3
    state: present

- name: Perform full upgrade
  command:
    cmd: apt full-upgrade -y
  become: yes
