- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Ensure /etc/apt/keyrings directory exists
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: docker_installed.rc != 0

- name: Add Docker's official GPG key
  become: yes
  get_url:
    url: "{{ docker_gpg_key_url }}"
    dest: "{{ docker_gpg_key_dest }}"
    mode: "a+r"
  vars:
    docker_gpg_key_url: "https://download.docker.com/linux/debian/gpg"
    docker_gpg_key_dest: "/etc/apt/keyrings/docker.asc"
  when: docker_installed.rc != 0

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    filename: docker
  vars:
    docker_gpg_key_dest: "/etc/apt/keyrings/docker.asc"
    docker_apt_repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by={{ docker_gpg_key_dest }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
  when: docker_installed.rc != 0

- name: Install Docker and related packages
  become: yes
  apt:
    name: docker-ce
    update_cache: yes
    state: present
  when: docker_installed.rc != 0

- name: Add Ansible user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: docker_installed.rc != 0

- name: Reset SSH connection to allow group add to take effect
  meta: reset_connection
