# code: language=ansible
- name: Install tools
  become: true
  apt:
    update_cache: true
    autoremove: true
    name:
      - ca-certificates
      - curl
      - openssh-server
      - vim
      - btop
      - dnsutils
      - iperf3
      - nftables
      - man
      - mc
      - zip
      - unzip
      - wget
      - gnupg2
      - rsync
      - debian-archive-keyring
      - python3-pip
      - python3-venv
      - python-is-python3
    state: present

- name: Perform full upgrade
  command:
    cmd: apt full-upgrade -y
  become: true
