# code: language=ansible
- name: Ensure journald configuration directory exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: '0755'

- name: Enforce maximum log size in journald
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/journald.conf.d/limits.conf
    content: |
      [Journal]
      SystemMaxUse=100M
      SystemMaxFileSize=100M
    owner: root
    group: root
    mode: '0644'
  register: journald_conf

- name: Restart systemd-journald to apply changes
  become: true
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  when: journald_conf.changed
