# code: language=ansible
#- name: Install necessary tools
#  ansible.builtin.import_tasks: install-tools.yaml

#- name: Install and configure systemd-networkd 
#  ansible.builtin.import_tasks: setup-systemd-networkd.yaml

#- name: Install and configure dnsmasq 
#  ansible.builtin.import_tasks: setup-dnsmasq.yaml

- name: Install and configure nftables 
  ansible.builtin.import_tasks: setup-nftables.yaml

#- name: Setup network
#  ansible.builtin.import_tasks: setup-network.yaml

#- name: Apply security settings
#  ansible.builtin.import_tasks: security-settings.yaml

#- name: Install Docker
 # ansible.builtin.import_tasks: install-docker.yaml
