# code: language=ansible
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: solaris2

- name: Configure ARP params 1
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_filter
    value: '1'
    state: present
    reload: true
    sysctl_set: true

- name: Configure ARP params 2
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_announce
    value: '2'
    state: present
    reload: true
    sysctl_set: true

- name: Configure ARP params 3
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_ignore
    value: '2'
    state: present
    reload: true
    sysctl_set: true
