---
# code: language=ansible
- name: Ensure other time synchronization mechanisms are disabled
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - systemd-timesyncd
    - ntp

- name: Install Chrony package
  become: true
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true

- name: Deploy custom chrony.conf file
  become: true
  ansible.builtin.copy:
    src: conf/chrony.conf # Adjust the path to where your file is located
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify:
    - Restart chrony

- name: Restart chrony
  become: true
  ansible.builtin.systemd:
    name: chrony
    state: restarted
