---
# code: language=ansible
- name: Create 'adguard' user
  ansible.builtin.user:
    name: adguard
    shell: /bin/false
    create_home: false

- name: Install required packages (e.g., curl for downloading AdGuard Home)
  ansible.builtin.apt:
    name:
      - curl
    state: present
    update_cache: true

- name: Download AdGuard Home
  ansible.builtin.get_url:
    url: https://github.com/AdguardTeam/AdGuardHome/releases/latest/download/AdGuardHome_linux_amd64.tar.gz
    dest: /tmp/AdGuardHome_linux_amd64.tar.gz
    mode: "0600"

- name: Extract AdGuard Home
  ansible.builtin.unarchive:
    src: /tmp/AdGuardHome_linux_amd64.tar.gz
    dest: /opt/
    remote_src: true

- name: Move AdGuard Home to its directory
  ansible.builtin.command: mv /opt/AdGuardHome*/ /opt/adguardhome
- name: Copy AdGuard Home configuration file
  ansible.builtin.copy:
    src: /path/to/local/AdGuardHome.yaml
    dest: /opt/adguardhome/AdGuardHome.yaml
    owner: adguard
    group: adguard
    mode: "0600"

- name: Create a systemd service file for AdGuard Home
  ansible.builtin.copy:
    dest: /etc/systemd/system/adguardhome.service
    content: |
      [Unit]
      Description=AdGuard Home
      After=network.target

      [Service]
      User=adguard
      Group=adguard
      ExecStart=/opt/adguardhome/AdGuardHome -c /opt/adguardhome/AdGuardHome.yaml
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start AdGuard Home service
  ansible.builtin.systemd:
    name: adguardhome
    enabled: true
    state: started
